### PR TITLE
 adding CF automate content

### PR DESCRIPTION
**Pull request by vestival**

### CODE REVIEW

**Comment by wrichter** [comment]
Hi Victor, I see that we're using some opaque binary files for now. Is there a way to create these ourselves (so we don't have to manage BLOBs)? Or were they downloaded by upload_cloudforms_content_rake_scripts.yml and should not have been checked in at all?

**Comment by vestival** [comment]
Hello!

Which files do you mean? Maybe I didn´t delete something… :(

**Comment by wrichter** [comment]
specifically CloudForms-Internals/dialogs.tar.gz, CloudForms-Internals/reports.tar.gz, CloudForms-Internals/zipfile.zip,

**Comment by vestival** [comment]
Sorry! Yeah, I need to delete them, because they are just temprary files.... I already cleaned them

**Comment by wrichter** [comment]
There's still CloudForms-Internals/zipfile.zip remaining. Btw. you can control what is going to be checked in by specifying a .gitignore file -> see the binary dir for an example.

Any particular reason you are not using the temp file name created using mktemp for the other tasks, instead using a hard-coded name?

**Comment by vestival** [comment]
I tried to use that temp name but… I could´t make it work, so I was planning to request your help tomorrow to clean it.

Zipfile is already removed in my system…

**Comment by wrichter** [comment]
yeah the BLOBs are gone. Let's look over the temp file bits tomorrow; I'll be in the office around 14:30 - I'll leave this request open until then

**Pull request merged**
